<a href="https://colab.research.google.com/github/tidocr0/THDeepLearning/blob/main/TH_HocSauBuoi01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

my_list = [1, 9, 15, 39]
print('Python list: ', my_list)

my_numpy_array = np.array(my_list)
print('Numpy array: ', my_numpy_array)



Python list:  [1, 9, 15, 39]
Numpy array:  [ 1  9 15 39]


In [ ]:
import numpy as np

c = np.array([(1, 2, 3), (4, 5, 6)])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [ ]:
import numpy as np

d = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10, 11, 12]]
])
print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


In [ ]:
import numpy as np

e = np.zeros((2, 2))
f = np.ones((3, 3))
print('Zero matrix: \n', e)
print('One matrix\n', f)

Zero matrix: 
 [[0. 0.]
 [0. 0.]]
One matrix
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import numpy as np

e = np.array([[1., 2., 3.], [4., 5., 6.]])
print(e)
print(e.shape)

g = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10., 11., 12.]]
])
print(g)
print(g.shape)

h = g.reshape(3, 4)
print('reshape (3, 4)\n', h)

j = g.reshape(3, 2, 2)
print('reshape (3, 2, 2)\n', j)

k = g.reshape(2, 3, 2)
print('reshape (2, 3, 2)\n', k)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
reshape (3, 4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3, 2, 2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2, 3, 2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


In [ ]:
import numpy as np

e = np.array([[1., 2., 3.], [4., 5., 6.]])
f = e.flatten()
print(f)

g = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10., 11., 12.]]
])
j = g.flatten()
print(j)

[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [ ]:
import numpy as np

f = np.array([1., 2., 3.])
g = np.array([4., 5., 6.])

h_stack = np.hstack((f, g))
print('Horizontal Append\n', h_stack)

v_stack = np.vstack((f, g))
print('Vertical Append\n', v_stack)

Horizontal Append
 [1. 2. 3. 4. 5. 6.]
Vertical Append
 [[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
import numpy as np

a = np.random.randint(100, size=(5,))
print('Random 1-D array\n', a)

b = np.random.randint(100, size=(3,4))
print('Random 2-D array\n', b)

c = np.random.randint(100, size=(3,4,3))
print('Random 3-D array\n', c)

Random 1-D array
 [47 48 83  8  2]
Random 2-D array
 [[97 68 83 86]
 [38 23 86 14]
 [80 14 15 59]]
Random 3-D array
 [[[ 0 37 52]
  [44 89 12]
  [13 48 70]
  [51 67 11]]

 [[24 93 59]
  [ 3  8 64]
  [78 91 99]
  [71 88 84]]

 [[ 0 12  0]
  [81 26 64]
  [21 23  3]
  [42 17 33]]]


In [ ]:
import numpy as np

a = np.random.rand(5)
print('Random 1-D array\n', a)

b = np.random.rand(3, 4)
print('Random 2-D array\n', b)

c = np.random.rand(3, 4, 3)
print('Random 3-D array\n', c)

Random 1-D array
 [0.36040809 0.95253234 0.2315981  0.67423556 0.38163175]
Random 2-D array
 [[0.53811935 0.19068661 0.82639479 0.61151524]
 [0.45396904 0.71211642 0.35279796 0.87027764]
 [0.96068146 0.51630031 0.9522454  0.4004148 ]]
Random 3-D array
 [[[0.52071674 0.84263074 0.59843745]
  [0.25688936 0.41856836 0.75268875]
  [0.66317865 0.09037251 0.19568276]
  [0.05776213 0.12289472 0.60810617]]

 [[0.56513332 0.80457775 0.28239289]
  [0.18071768 0.0872144  0.29802023]
  [0.45723457 0.80703574 0.01729132]
  [0.24733538 0.66642286 0.59196611]]

 [[0.82458018 0.06839666 0.83707219]
  [0.35907778 0.42141463 0.86831493]
  [0.11755051 0.46005616 0.14298815]
  [0.91915407 0.16807192 0.23600851]]]


In [ ]:
import numpy as np

a = np.random.normal(5, 0.5, 10)
print(a)

[4.64855458 5.44263928 4.67368214 5.5947479  5.70886965 5.41886032
 4.97160641 5.48502229 5.83013153 5.31091592]


In [ ]:
import numpy as np

a = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
print(a)

b = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20], size=(3,5))
print(b)

20
[[ 6 10 10 14 14]
 [16 12 12  6 14]
 [ 8 20 14 16 20]]


In [ ]:
import numpy as np

A = np.matrix(np.ones((5,5)))
print('The matrix\n', A)

np.array(A)[2] = 2
print('Change values of third row with array\n', A)

np.asarray(A)[2] = 2
print('Change values of third row with asarray\n', A)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
import numpy as np

a = np.arange(1, 20)
print(a)

b = np.arange(1, 20, 2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
import numpy as np

a = np.linspace(1., 5., num=10)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [ ]:
import numpy as np

a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print('first row:', a[0])
print('second row:', a[1])

print('Second column:', a[:,1])
print('first column', a[:, 0])
print('First two values of second row:', a[1, :2])

[[1 2 3]
 [4 5 6]]
first row: [1 2 3]
second row: [4 5 6]
Second column: [2 5]
first column [1 4]
First two values of second row: [4 5]


In [ ]:
import pandas as pd

a = pd.Series([1.,2.,3.])