<a href="https://colab.research.google.com/github/tidocr0/THDeepLearning/blob/main/TH_HocSauBuoi01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

my_list = [1, 9, 15, 39]
print('Python list: ', my_list)

my_numpy_array = np.array(my_list)
print('Numpy array: ', my_numpy_array)



Python list:  [1, 9, 15, 39]
Numpy array:  [ 1  9 15 39]


In [10]:
import numpy as np

c = np.array([(1, 2, 3), (4, 5, 6)])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [11]:
import numpy as np

d = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10, 11, 12]]
])
print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


In [12]:
import numpy as np

e = np.zeros((2, 2))
f = np.ones((3, 3))
print('Zero matrix: \n', e)
print('One matrix\n', f)

Zero matrix: 
 [[0. 0.]
 [0. 0.]]
One matrix
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
import numpy as np

e = np.array([[1., 2., 3.], [4., 5., 6.]])
print(e)
print(e.shape)

g = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10., 11., 12.]]
])
print(g)
print(g.shape)

h = g.reshape(3, 4)
print('reshape (3, 4)\n', h)

j = g.reshape(3, 2, 2)
print('reshape (3, 2, 2)\n', j)

k = g.reshape(2, 3, 2)
print('reshape (2, 3, 2)\n', k)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
reshape (3, 4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3, 2, 2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2, 3, 2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


In [14]:
import numpy as np

e = np.array([[1., 2., 3.], [4., 5., 6.]])
f = e.flatten()
print(f)

g = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10., 11., 12.]]
])
j = g.flatten()
print(j)

[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [15]:
import numpy as np

f = np.array([1., 2., 3.])
g = np.array([4., 5., 6.])

h_stack = np.hstack((f, g))
print('Horizontal Append\n', h_stack)

v_stack = np.vstack((f, g))
print('Vertical Append\n', v_stack)

Horizontal Append
 [1. 2. 3. 4. 5. 6.]
Vertical Append
 [[1. 2. 3.]
 [4. 5. 6.]]


In [16]:
import numpy as np

a = np.random.randint(100, size=(5,))
print('Random 1-D array\n', a)

b = np.random.randint(100, size=(3,4))
print('Random 2-D array\n', b)

c = np.random.randint(100, size=(3,4,3))
print('Random 3-D array\n', c)

Random 1-D array
 [58 48 85 19  5]
Random 2-D array
 [[92 20 58 21]
 [94 25 24 47]
 [64  4 39 40]]
Random 3-D array
 [[[10 30 42]
  [10  9 27]
  [36 41 76]
  [68 24 61]]

 [[14 74 91]
  [26 78 52]
  [89 25  7]
  [65 90 94]]

 [[11 98 74]
  [72 57 21]
  [65  4 17]
  [73 24 11]]]


In [17]:
import numpy as np

a = np.random.rand(5)
print('Random 1-D array\n', a)

b = np.random.rand(3, 4)
print('Random 2-D array\n', b)

c = np.random.rand(3, 4, 3)
print('Random 3-D array\n', c)

Random 1-D array
 [0.17873401 0.78878761 0.10302471 0.29762253 0.40989906]
Random 2-D array
 [[0.67203081 0.86885606 0.6529046  0.75892171]
 [0.94917856 0.53826359 0.60415528 0.74925927]
 [0.14202156 0.88176447 0.72761875 0.58952554]]
Random 3-D array
 [[[0.72186297 0.99419462 0.43054427]
  [0.9767094  0.49740029 0.60444054]
  [0.15536361 0.48521019 0.03777041]
  [0.69972054 0.95642715 0.05161995]]

 [[0.61441805 0.1753649  0.26070107]
  [0.6600916  0.79068387 0.9690743 ]
  [0.53608291 0.02295171 0.79803593]
  [0.26374033 0.19640412 0.03391004]]

 [[0.22886936 0.07721176 0.24458748]
  [0.34134877 0.18407454 0.8382134 ]
  [0.95146972 0.52342873 0.33711569]
  [0.74186934 0.65943192 0.46419767]]]


In [18]:
import numpy as np

a = np.random.normal(5, 0.5, 10)
print(a)

[4.47254386 5.31186391 5.03688171 4.61769199 5.24472969 5.4299312
 4.87310073 5.12659259 5.11387752 5.37041083]


In [19]:
import numpy as np

a = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
print(a)

b = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20], size=(3,5))
print(b)

10
[[14 20  8 18 14]
 [ 2  2 16 20  2]
 [10 18 16 20  4]]


In [20]:
import numpy as np

A = np.matrix(np.ones((5,5)))
print('The matrix\n', A)

np.array(A)[2] = 2
print('Change values of third row with array\n', A)

np.asarray(A)[2] = 2
print('Change values of third row with asarray\n', A)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [21]:
import numpy as np

a = np.arange(1, 20)
print(a)

b = np.arange(1, 20, 2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


In [22]:
import numpy as np

a = np.linspace(1., 5., num=10)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [23]:
import numpy as np

a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print('first row:', a[0])
print('second row:', a[1])

print('Second column:', a[:,1])
print('first column', a[:, 0])
print('First two values of second row:', a[1, :2])

[[1 2 3]
 [4 5 6]]
first row: [1 2 3]
second row: [4 5 6]
Second column: [2 5]
first column [1 4]
First two values of second row: [4 5]


In [24]:
import pandas as pd

a = pd.Series([1., 2., 3.])
print(a)
print('First value:', a[0])
b = pd.Series([1., 2., 3.], index=['a', 'b', 'c'])
print(b)
print('First value:', b['a'])
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)

0    1.0
1    2.0
2    3.0
dtype: float64
First value: 1.0
a    1.0
b    2.0
c    3.0
dtype: float64
First value: 1.0
day1    420
day2    380
day3    390
dtype: int64


In [25]:
import pandas as pd
import numpy as np

h = np.array([[1, 2], [3, 4]])
df_h = pd.DataFrame(h)
print('DataFrame:\n', df_h)

numpy_h = np.array(df_h)
print('Numpy array: \n', numpy_h)

DataFrame:
    0  1
0  1  2
1  3  4
Numpy array: 
 [[1 2]
 [3 4]]


In [26]:
import pandas as pd

dic = {'Name':['John', 'Smith'], 'Age':[30, 40]}
df_dic = pd.DataFrame(dic)
print(df_dic)

    Name  Age
0   John   30
1  Smith   40


In [27]:
import numpy as np
import pandas as pd

#tạo mảng 20 x 4
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head()) #in 5 dòng đầu tiên [cite: 414]

        so1       so2       so3       so4
0  0.340255 -1.066681 -0.549648  1.345125
1  1.051110  0.645510 -0.489908  0.981271
2  0.287012 -0.124464 -0.228603 -0.098130
3  1.009692  2.735902 -1.201323  0.428713
4 -2.352439  0.780909 -1.363377  1.631073


In [28]:
import numpy as np
import pandas as pd

#tạo mảng 20 x 4
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head())  #in 5 dòng đầu tiên

#chọn 1 cột
print('Chọn cột so1\n', df['so1'])

#chọn nhiều dòng
print('Chọn nhiều dòng\n', df[0:3])

#chọn nhiều cột
print('Chọn nhiều cột\n', df[['so1', 'so3']])

#chọn nhiều dòng, nhiều cột
print('Chọn nhiều dòng, nhiều cột\n', df.iloc[:3, :2])

#Xóa cột
df = df.drop(columns=['so1', 'so4'])
print(df)

        so1       so2       so3       so4
0  2.697098 -1.305473 -0.325368  0.530161
1  0.944428  0.335103 -0.386171  0.857647
2 -1.875171 -1.769922 -2.147310  0.572020
3 -0.364590 -1.056898 -1.600513  0.280745
4  0.376033 -2.335239 -0.377904 -0.449544
Chọn cột so1
 0     2.697098
1     0.944428
2    -1.875171
3    -0.364590
4     0.376033
5     0.237584
6     0.310269
7     1.231684
8    -0.203060
9     1.418036
10    1.085434
11    0.847918
12   -1.593504
13   -0.877443
14    0.046706
15   -0.296396
16   -0.349275
17    0.233390
18   -2.310398
19    2.221789
Name: so1, dtype: float64
Chọn nhiều dòng
         so1       so2       so3       so4
0  2.697098 -1.305473 -0.325368  0.530161
1  0.944428  0.335103 -0.386171  0.857647
2 -1.875171 -1.769922 -2.147310  0.572020
Chọn nhiều cột
          so1       so3
0   2.697098 -0.325368
1   0.944428 -0.386171
2  -1.875171 -2.147310
3  -0.364590 -1.600513
4   0.376033 -0.377904
5   0.237584  0.264728
6   0.310269  1.176948
7   1.231684 -0.141841


In [29]:
import pandas as pd

#Nối 2 DataFrame [cite: 448]
df1 = pd.DataFrame({'Name':['John', 'Smith', 'Paul'],
                    'Age':[25, 30, 50]
                    }, index=[0, 1, 2])
df2 = pd.DataFrame({'Name':['Adam', 'Smith'],
                    'Age':[26, 11]
                    }, index=[3, 4])
df_concat = pd.concat([df1, df2])
print('Concate two DataFrame\n', df_concat)

#Xóa những giá trị ở cột Name trùng nhau
print('Drop duplicatevalues in DataFrame\n', df_concat.drop_duplicates('Name'))

#Sắp xếp theo cột [cite: 461]
print('Sort values in DataFrame\n', df_concat.sort_values('Age'))

#Đổi tên cột [cite: 462]
df_rename = df_concat.rename(columns={'Name':'Surname', 'Age':'Age_pupil'})
print('Rename columns of DataFrame\n', df_rename)

Concate two DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
4  Smith   11
Drop duplicatevalues in DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
Sort values in DataFrame
     Name  Age
4  Smith   11
0   John   25
3   Adam   26
1  Smith   30
2   Paul   50
Rename columns of DataFrame
   Surname  Age_pupil
0    John         25
1   Smith         30
2    Paul         50
3    Adam         26
4   Smith         11


In [30]:
import tensorflow as tf

rank_0_tensor = tf.constant(4)
print(rank_0_tensor)
r1 = tf.constant(9, tf.int16)
print(r1)
r1_float = tf.constant(1.12, tf.float32)
print(r1_float)
r1_string = tf.constant('Hello VanLang University', tf.string)
print(r1_string)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello VanLang University', shape=(), dtype=string)


In [31]:
import tensorflow as tf

rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [ ]:
rank_2_tensor = tf.constant([1, 2],
                            )